name: 01-Building Blocks
on:
  - workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: failed_step
        run: | 
          echo "I"
          echo "Have"
          echo "Failed"
      
      - name: say goodbye
        run: echo "Goodbye"
